hello:
	echo hello greg - may you be happy and free from suffering

test:
	python3 api_etm.py


example:
	echo python3 api_etm.py -i out/DelawareRiverBasin/Run09_13_2020/ -o enduser/DelawareRiverBasin/Run09_13_2020/ward_sandford_customer/ -y 2003 etasw netet

